language: python
version:
    - 2.7
notifications:
    email:
        recipients:
            - hoye@ualberta.ca
        on_success: always
        on_failure: always
before_install: 
    - sudo apt-get install spim
script: python spim-grader.py
